# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(workflows)
    library(xgboost)
}
b <- board_folder(path = "/var/folders/ml/6750yrxn1ds3gsf4d8b6bb600000gn/T/RtmpQGaLaS/pins-113c17c9d1b4e")
v <- vetiver_pin_read(b, "boosted-chicago", version = "20260201T205357Z-b3640")

#* @plumber
function(pr) {
    pr |> vetiver_api(v)
}
